type: imagenet
version: 0.1
config:
    model:
        type: efficientnet_b2
        kwargs:
            bn:
                use_sync_bn: False
                kwargs:
                    momentum: 0.99

    dist:
        sync: False

    optimizer:
        type: FP16RMSprop
        kwargs:
            alpha: 0.9
            momentum: 0.9
            eps: 0.02
            weight_decay: 0.00001
        pconfig:
            bn_b:
                weight_decay: 0.0
            bn_w:
                weight_decay: 0.0
        fp16_normal_bn: True

    lr_scheduler:
        type: StepDecay
        kwargs:
            base_lr: 0.001
            warmup_lr: 0.064
            warmup_steps: 2500
            step_size: 1714
            decay: 0.97
            max_iter: 250000

    label_smooth: 0.1
    ema:
        enable: True
        kwargs:
            decay: 0.999
    

    data:
        use_dali: False
        use_dali_v2: True
        read_from: mc
        batch_size: 64
        dali_workers: 4
        workers: 2
        pin_memory: True
        epoch_wise_shuffle: True

        input_size: 260
        test_resize: 292
        augmentation:
            colorjitter: [0.2, 0.2, 0.2, 0.1]
        train_root: /mnt/lustre/share/images/train
        train_meta: /mnt/lustre/share/images/meta/train.txt
        val_root: /mnt/lustre/share/images/val
        val_meta: /mnt/lustre/share/images/meta/val.txt

    print_freq: 10
    val_freq: 1000
    save_many: True
