image: "python:3.6"

#before_script:
#    - pip install flake8

stages:
    - style_check
    - test
    

flake8:
    stage: style_check
    tags:
        - docker
    script:
        - pip install flake8
        - python -m flake8 --max-line-length=120

test_main:
    stage: test
    tags:
        - docker
    script:
        - python main.py
