image: "python:3.6"

#before_script:
#    - pip install flake8

stages:
    - style_check
    - test
    

flake8:
    stage: style_check
    script:
        - pip install flake8
        - python -m flake8

test_main:
    stage: test
    script:
        - python main.py
