model:
    type: efficientnet_b0
    kwargs:
        bn:
            use_sync_bn: False
            kwargs:
                momentum: 0.99

dist:
    sync: False

optimizer:
    type: FP16RMSprop
    fp16_normal_bn: True
    kwargs:
        alpha: 0.9
        momentum: 0.9
        eps: 0.02
        weight_decay: 0.00001
    pconfig:
        bn_b:
            weight_decay: 0.0
        bn_w:
            weight_decay: 0.0

lr_scheduler:
    type: StepDecay
    kwargs:
        base_lr: 0.001
        warmup_lr: 0.064
        warmup_steps: 2500
        step_size: 1714
        decay: 0.97
        max_iter: 437500

label_smooth: 0.1
# mixup: 0.2
# cutmix: 1.0
ema:
    enable: True
    kwargs:
        decay: 0.999

lms:
    enable: False
    kwargs:
        limit: 12

data:
    type: imagenet
    read_from: mc
    use_dali: True
    batch_size: 64
    num_workers: 4
    pin_memory: True
    input_size: 224
    test_resize: 256

    train:
        root_dir: /mnt/lustre/share/images/train/
        meta_file: /mnt/lustre/share/images/meta/train.txt
        image_reader:
            type: pil
        sampler:
            type: distributed_iteration
        transforms:
            type: STANDARD

    test:
        root_dir: /mnt/lustre/share/images/val/
        meta_file: /mnt/lustre/share/images/meta/val.txt
        image_reader:
            type: pil
        sampler:
            type: distributed
        transforms:
            type: ONECROP
        evaluator:
            type: imagenet
            kwargs:
                topk: [1, 5]

saver:
    print_freq: 10
    val_freq: 1000
    save_many: False
    # pretrain:
    #     path: checkpoints/ckpt.pth.tar
    #     ignore:
    #         key:
    #             - optimizer
    #             - last_iter
    #         model:
    #             - module.fc.weight
    #             - module.fc.bias
