type: imagenet
version: 0.1
config:
    model:
        type: resnet101
        kwargs:
            bn:
                use_sync_bn: False
                kwargs: {}
            deep_stem: True
            avg_down: True

    dist:
        sync: False

    optimizer:
        type: FusedFP16SGD
        kwargs:
            nesterov: True
            momentum: 0.9
            weight_decay: 0.0001
        fp16_normal_bn: True

    lr_scheduler:
        type: Cosine
        kwargs:
            base_lr: 0.1
            warmup_lr: 0.4
            min_lr: 0.0
            warmup_steps: 2500
            max_iter: 250000

    label_smooth: 0.1
    mixup: 0.2
    ema:
        enable: False

    data:
        use_dali: False
        use_dali_v2: True
        read_from: mc
        batch_size: 64
        dali_workers: 4
        workers: 2
        pin_memory: True
        epoch_wise_shuffle: False

        input_size: 224
        test_resize: 256
        augmentation:
            colorjitter: [0.2, 0.2, 0.2, 0.1]
        train_root: /mnt/lustre/share/images/train
        train_meta: /mnt/lustre/share/images/meta/train.txt
        val_root: /mnt/lustre/share/images/val
        val_meta: /mnt/lustre/share/images/meta/val.txt

    print_freq: 10
    val_freq: 1000
    save_many: False
