type: imagenet
version: 0.1
config:
    model:
        type: resnet50_official
        kwargs:
            num_classes: 128
            bn:
                use_sync_bn: False
                kwargs: {}

    dist:
        sync: True

    moco:
        kwargs:
            K: 65536
            T: 0.2
            m: 0.999
            mlp: True
            group_size: 8

    optimizer:
        type: SGD
        fp16_normal_bn: False
        kwargs:
            nesterov: True
            momentum: 0.9
            weight_decay: 0.0001

    lr_scheduler:
        type: Cosine
        kwargs:
            base_lr: 0.06
            warmup_lr: 0.06
            warmup_steps: 0
            min_lr: 0.0
            max_iter: 500000

    ema:
        enable: False

    data:
        use_dali: False
        use_dali_v2: False
        moco_protocol: True
        read_from: mc
        batch_size: 32
        dali_workers: 4
        workers: 2
        pin_memory: True
        epoch_wise_shuffle: False

        input_size: 224
        test_resize: 256
        augmentation:
            type: moco_v2
        train_root: /mnt/lustre/share/images/train
        train_meta: /mnt/lustre/share/images/meta/train.txt
        val_root: /mnt/lustre/share/images/val
        val_meta: /mnt/lustre/share/images/meta/val.txt

    print_freq: 10
    save_freq: 10000
    save_many: False
