model:
    type: resnet50_official
    kwargs:
        num_classes: 128
        bn:
            use_sync_bn: False
            kwargs: {}

dist:
    sync: True

moco:
    kwargs:
        K: 65536
        T: 0.07
        m: 0.999
        mlp: False
        group_size: 16

optimizer:
    type: SGD
    kwargs:
        nesterov: True
        momentum: 0.9
        weight_decay: 0.0001

lr_scheduler:
    type: Step
    kwargs:
        lr_steps: [300000, 400000]
        lr_mults: [0.1, 0.1]
        base_lr: 0.06
        warmup_lr: 0.06
        warmup_steps: 0
        max_iter: 500000

ema:
    enable: False

data:
    type: imagenet
    read_from: mc
    use_dali: False
    batch_size: 32
    num_workers: 4
    pin_memory: True
    input_size: 224
    test_resize: 256

    train:
        root_dir: /mnt/lustre/share/images/train/
        meta_file: /mnt/lustre/share/images/meta/train.txt
        image_reader:
            type: pil
        sampler:
            type: distributed_iteration
        transforms:
            type: MOCOV1

saver:
    print_freq: 10
    val_freq: 5000
    save_many: True
