model:
    type: resnet50_official
    kwargs:
        num_classes: 128
        bn:
            use_sync_bn: False
            kwargs: {}

dist:
    sync: True

moco:
    kwargs:
        K: 65536
        T: 0.2
        m: 0.999
        mlp: True

optimizer:
    type: SGD
    fp16_normal_bn: False
    kwargs:
        nesterov: True
        momentum: 0.9
        weight_decay: 0.0001

lr_scheduler:
    type: Cosine
    kwargs:
        base_lr: 0.03
        warmup_lr: 0.03
        warmup_steps: 0
        min_lr: 0.0
        max_iter: 1000000

ema:
    enable: False

data:
    type: imagenet
    read_from: mc
    use_dali: False
    batch_size: 32
    num_workers: 4
    pin_memory: True
    input_size: 224
    test_resize: 256

    train:
        root_dir: /mnt/lustre/share/images/train/
        meta_file: /mnt/lustre/share/images/meta/train.txt
        image_reader:
            type: pil
        sampler:
            type: distributed_iteration
        transforms:
            type: MOCOV2

saver:
    print_freq: 10
    val_freq: 5000
    save_many: True
